### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by AseelAlshorafa** [MagedSaeed/farasapy#11]
Hello, 
thanks for your effort in developing this useful library 
I used it multiple times before, at this time I used the same code but an error occurred 
can you please help me 

[2020-12-14 14:02:59,134 - farasapy_logger - ERROR]: an error occured
[2020-12-14 14:02:59,135 - farasapy_logger - ERROR]: HTTPSConnectionPool(host='farasa-api.qcri.org', port=443): Max retries exceeded with url: /farasapy/releases/download/toolkit-bins-released/farasa_bin.zip (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

**Comment by MagedSaeed** [comment]
Thanks for reporting such issue. It seems that this is a problem with farasa team in delivering the required binaries. I will check with them and provide my updates. Again, thanks for reporting such issue.

**Comment by RomainBsb** [comment]
Hello Maged, any update on this issue? Thanks a lot for your help

**Comment by MagedSaeed** [comment]
I already have sent an email with the issue. Waiting for their response. I hope they will reply to us soon!

**Comment by MagedSaeed** [comment]
@AseelAlshorafa ,
@RomainBsb 

The problem has been resolved. I am thankful for Farasa maintainers for their prompt response and quick fix. Please check and confirm. Please close the issue if you do not have any further concerns.

Here is the tests notebook so that you can try on the fly:

[https://colab.research.google.com/drive/1xjzYwmfAszNzfR6Z2lSQi3nKYcjarXAW#scrollTo=wkovt8hvTabq]

**Comment by RomainBsb** [comment]
@MagedSaeed , that's working very well on my side! Thanks for the quick fix

**Comment by AseelAlshorafa** [comment]
The problem is solved, Thanks for the fast response

**Comment by MagedSaeed** [comment]
Thanks for staying tuned,.
