### ISSUE TITLE
Spell Checker

### ISSUE THREAD

**Issue by OmarMohammed88** [MagedSaeed/farasapy#12]
why the spell checker is not provided in the repository?

**Comment by MagedSaeed** [comment]
Hey omar

Sorry for the late response.

This wrapper only wraps the jar binaries provided by the authors in farasa website [http://qatsdemo.cloudapp.net/farasa/] except the concistency parser. I may add it in the future.

But you can ask farasa authors "I am not one of them" to provide it as a Java jar and I will be happy to add it. If you will communicate with them through email, please put me on cc so that I will be updated. 

Thanks,.

**Comment by OmarMohammed88** [comment]
Ok thank u very much
