### ISSUE TITLE
How to use farasapy completely offline

### ISSUE THREAD

**Issue by atytxt** [MagedSaeed/farasapy#18]
How I can use Farasapy without internet connection? is there any way to download and install package and use it offline later?

**Comment by MagedSaeed** [comment]
Actually, farasapy will check for the binaries at the begining. If they do exist, then it won't download them. Otherwise, it will download them and save them in a local directory on your machine. So, the internet connection is only needed once, in the first run. Afterwards, no need for download unless you manually deleted them.

I can understand the confusion if you always run it from colab where binaries are downloaded everytime. However, this should not be the case if it is installed on your local machine.

Hope this answers your question.

**Comment by MagedSaeed** [comment]
closed for inactivity

**Comment by atytxt** [comment]
So this means that there is no need to download anything before and after first run?

**Comment by MagedSaeed** [comment]
I am not sure if docker would work for you. However, you are true that you just need to only run it once to download the binaries.

**Comment by AsmaZbt** [comment]
hello @atytxt , did you used farasapy completely offline? if you did , can you show me how to do that please? 
thank you so much

**Comment by atytxt** [comment]
Hello, No I could not use it offline. I am using the base preprocess
instead.
