### ISSUE TITLE
Initializing the system repeat and how to define the model path myself

### ISSUE THREAD

**Issue by liutianling** [MagedSaeed/farasapy#2]
@MagedSaeed
Thanks for your work! It's great.
But I have some problems when using it.
1、It will repeat Initializing the system when I do the ner task in a look as follows:
ner = FarasaNamedEntityRecognizer()
for i in range(3):
	ners = ner.recognize(sample)
	print(ners)
	print(type(ners))

It is very slow and the momery is growing up ...

2. If it support defining the model path by myself. I think it will be more convenient..

**Comment by MagedSaeed** [comment]
Hey @liutianling 

Thanks for your feedback.

For your first point:
It is expected, in this implementation you followed, to be slow. Actually, you are calling the model every time you are calling the task `recognize(sample)`. This option is convenient only when you are doing the task once and on a large text.

For your case, it seems that the best approach is to initialize the object in interactive mode. Interactive mode will open the model interactively on the object instantiation (it will only take some time here). This approach is relatively very fast on doing tasks but may break when you have _large lines_. To initialize the object in interactive mode, you just need to pass the option `interactive=True` on object construction as follows:

```
ner = FarasaNamedEntityRecognizer(interactive=True)
for _ in range(3):
    print(ner.recognize('whatever text you have')
```
Please try the interactive mode and provide your feedback.

For your second point, I think it is very convenient to pack all the package dependencies in one place. However, providing such an option is not a bad idea. Actually, the current implementation will download the whole binaries if only one is missing instead of downloading only the missing one. We will try to improve upon this feature in the upcoming updates. We, also, will try to take a look at such an option. Your contribution, by the way, is highly appreciated.

**Comment by MagedSaeed** [comment]
@liutianling 

Please take a look at these examples:

https://colab.research.google.com/drive/1xjzYwmfAszNzfR6Z2lSQi3nKYcjarXAW?usp=sharing

**Comment by liutianling** [comment]
@MagedSaeed Thanks!
Thanks for your help.
Then , another question.
Do you know the mothod of farasa use？such as crf、lstm or bert etc..
Do you konw the score such as f1 of it, or have you tested ?

**Comment by liutianling** [comment]
@MagedSaeed Have test the max length of the long line in interactive mode?
It seems it can solve by sentence split before nlp process.
Can the arabic text do sentence spliting the same as english?
I am sorry for my bad english. Please forgive me. Thanks.

**Comment by MagedSaeed** [comment]
@liutianling 

I did not dive much in all the models but they gave an introduction in their main page and papers. For segmentation,at least, I think they used SVMs and benchmark it with MADAMIRA, the state of the art.

**Comment by MagedSaeed** [comment]
@liutianling 

You are true, we can split on a fixed size of characters or tokens. However, this might be dangerous for the model if the sequences are dependent. It is better to feed the whole text, or split on optimal places.

**Comment by MagedSaeed** [comment]
I am going to close this issue. Please consider contacting me for any further inquires.

**Comment by liutianling** [comment]
@MagedSaeed OK! Thanks for your work and help.
