### ISSUE TITLE
question about the result of segmentor

### ISSUE THREAD

**Issue by liutianling** [MagedSaeed/farasapy#5]
@MagedSaeed Hi, my friends . I have some questions when using the farase. I want to get your help, thanks.

sample =\
''' 
يُشار إلى أن اللغة العربية يتحدثها أكثر من 422 مليون نسمة ويتوزع متحدثوها
 في المنطقة المعروفة باسم الوطن العربي بالإضافة إلى العديد من المناطق ال
أخرى المجاورة مثل الأهواز وتركيا وتشاد والسنغال وإريتريا وغيرها.وهي اللغ
ة الرابعة من لغات منظمة الأمم المتحدة الرسمية الست. 
'''
print('----------------------------------------')
print("Farasa features, interactive mode.")
print('----------------------------------------')

segmenter_interactive = FarasaSegmenter(interactive=True)
segmented_interactive = segmenter_interactive.segment(sample)
print("sample segmented (interactive):",segmented_interactive)
print("----------------------------------------------")

sample segmented (interactive): يشار إلى أن ال+لغ+ة ال+عربي+ة يتحدث+ها أكثر من 422 مليون نسم+ة و+يتوزع متحدثوها
في ال+منطق+ة ال+معروف+ة باسم ال+وطن ال+عربي ب+ال+إضاف+ة إلى ال+عديد من ال+مناطق ال
أخرى ال+مجاور+ة مثل ال+أهواز و+تركيا و+تشاد و+ال+سنغال و+إريتريا و+غير+ها . و+هي ال+لغ
+ه ال+رابع+ة من لغ+ات منظم+ة ال+أمم ال+متحد+ة ال+رسمي+ة ال+ست .

The result of the segmenter has show above.
(1) I want to know if i want to get the list of the word, just split the result by '+' or some other way ?
(2) I don't sure if the arabic text can just split by the space as english ? If it works, the result seems don't match the result get by farasa.
(3) If i want to split the text by sentence, how can i do it?
Thanks so much.

**Comment by MagedSaeed** [comment]
Hey @liutianling 

Actually, the nature of Arabic is quite complecated. It is very common for Arabic words to be conjugated with suffixes and prefixes, sometimes many of them. What Farasa is doing is that it  disjoins these words from their affixes. It split them by the char "+". The list of these affixes is mentioned the toolkit authors paper "website referenced in the README".  
1. In order to get the list of words, based on the above discussion, you can split by spaces then split each token by + then clean the affixes list. I hope this makes sense.
2. I did not get it but I think it is related to the previous point. Please elaborate more.
3. For sentences, the "." char is used. But some other charachters might be informally used such as "،" and "؛". Also, it is safe to split by newlines.

I hope that was helpful. Please mention anything that is not clear.

**Comment by liutianling** [comment]
@MagedSaeed Thanks very much.
It really helps me.
