### ISSUE TITLE
Problems when using library in google colab

### ISSUE THREAD

**Issue by Mahmo0odsalah** [MagedSaeed/farasapy#8]
I tried to use the library in my colab project. And whenever I ran the same cells as the notebook linked in the readme file, I get the same error in Standalone mode.

![image](https://user-images.githubusercontent.com/26148101/84628178-75c96500-aee8-11ea-996a-3bfbb4d26575.png)

**Comment by MagedSaeed** [comment]
Thanks for reporting such issue. Actually, this is because the initial `farasapy` code was not python=3.6 compatible. We, then, amended the code to be so but forgot to check that after fixing a bug for windows platform.

Now, it is fine. Please double-check in the notebook.

https://colab.research.google.com/drive/1xjzYwmfAszNzfR6Z2lSQi3nKYcjarXAW#scrollTo=wkovt8hvTabq

**Comment by Mahmo0odsalah** [comment]
Great, I just checked and it works perfectly. Thanks for the library and for the quick response. Keep the hard work.
